name: farmsonic_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  wifi_iot: ^0.3.19+1
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0
  get: ^4.6.6
  flutter_inappwebview: ^6.1.4
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/인트로로고.png
    - assets/icon/appstore.png
    - assets/icon/playstore.png

# 이 섹션을 'flutter' 블록 외부에 배치해야 합니다.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/playstore.png"
  image_path_android: "assets/icon/playstore.png"
  image_path_ios: "assets/icon/appstore.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

